### ISSUE TITLE
read_one can not be used

### ISSUE THREAD

**Issue by MornNighter** [arc-instruments/libarc1#1]
As newest Firmware is utilized, the read_one instruction can not be used, as it will get error:

    return self.read_floats(1)[0]
    IndexError: index 0 is out of bounds for axis 0 with size 0

my code is like:

    from libarc1 import ArC1
    arc1 = ArC1('com3')
    arc1.select(1, 1)
    arc1.pulse_active(2.5, 100e-6)
    arc1.read_one(1, 1)

**Comment by foucault** [comment]
Hello! I'm afraid I cannot replicate the problem. I tried the following script on two different Windows 10 computers and a Linux computer

```python
from libarc1 import ArC1

arc1 = ArC1('COM3') # or /dev/ttyXXX for Linux
arc1.select(1, 1)
arc1.pulse_active(2.5, 100e-6)
print(arc1.read_one(1, 1))

arc1.close()
```
Returns `1289594200.0` or thereabouts with (1, 1) being an open crosspoint. Have you ensured you have the [latest mbed drivers](https://os.mbed.com/handbook/Windows-serial-configuration) for Windows? It shouldn't really be necessary but Windows Update had messed up with serial port drivers before. I would also try a different USB port if possible. Any more information you can provide is welcome.

**Comment by MornNighter** [comment]
> Hello! I'm afraid I cannot replicate the problem. I tried the following script on two different Windows 10 computers and a Linux computer
> 
> ```python
> from libarc1 import ArC1
> 
> arc1 = ArC1('COM3') # or /dev/ttyXXX for Linux
> arc1.select(1, 1)
> arc1.pulse_active(2.5, 100e-6)
> print(arc1.read_one(1, 1))
> 
> arc1.close()
> ```
> 
> Returns `1289594200.0` or thereabouts with (1, 1) being an open crosspoint. Have you ensured you have the [latest mbed drivers](https://os.mbed.com/handbook/Windows-serial-configuration) for Windows? It shouldn't really be necessary but Windows Update had messed up with serial port drivers before. I would also try a different USB port if possible. Any more information you can provide is welcome.

Hello! As you said, I reinstalled the driver, and it work now! 
This problem may be associated with Windows Update.
Thank you very much!
